### ISSUE TITLE
Problem with finding files

### ISSUE THREAD

**Issue by mmb-bioinf** [lerxst1967/Spyral#1]
Hi, I just wanted to try out your script, but I always run into following issue:
Wether I select a folder or a single mp3 file, the script yields an error, stating that it can't find the chosen file:

PS C:\Users\MMB\Desktop\yt2mp3> python .\spyral6.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
BABY B3NS - Schmetterling (Rolexz Remix).mp3
Traceback (most recent call last):
  File "C:\Users\MMB\Desktop\yt2mp3\spyral6.py", line 382, in <module>
    subprocess.call(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
PS C:\Users\MMB\Desktop\yt2mp3>

I also tried the .exe from your yt vid, but it just resulted in a pop up stating that a fatal error occured. I'm using Windows 11 and Python 3.11.
I"d appreciate any help, as the script looks very promising!

**Comment by mmb-bioinf** [comment]
I found the issue myself... I didn't have ffmpeg installed. Please list dependencies somewhere.
